### ISSUE TITLE
Possible memory leak in post feeds

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#152]
1. Make sure there are a number of posts with images available for a current user in different post feeds
2. Launch the app
3. Switch between feeds, swipe them to load posts from further pages and check memory allocation (e.g. in XCode debug navigator) while switching and swiping

Current result:
Switching between feeds and swiping them continuously increases memory allocation, switching from one feed to another doesn't decrease memory allocation

**Comment by orezhko** [comment]
fixed after migration from UiTextField to UILabel in feeds
