### ISSUE TITLE
API returns weird result using limit 3

### ISSUE THREAD

**Issue by IgorPopov-MS** [Microsoft/EmbeddedSocial-iOS-SDK#171]
Following request 
{{base_path}}/{{api_version}}/users/me/following/combined?limit=3

produces this output:

"{
    "data": [],
    "cursor": "3tumB-1ssxy"
}"

but when limit is changed to "?limit=4" i get proper output with correct feed.

Anyway, its not blocking us.

**Comment by orezhko** [comment]
changed the logic to support that
