### ISSUE TITLE
rapidly scrolling down a topic feed results in a temporarily hung UI

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#255]
- go to popular topics feed
- very quickly scroll down (i.e. swipe up on screen)
- UI temporarily freezes
- after several seconds, the spinner appears and then continues loading

**Comment by orezhko** [comment]
Jaroslaw, could you please verify behavior on the latest build

**Comment by JaroslawRomanovich** [comment]
Verified on build from commit number e3e420b308ff6a043ac652983c64ca130dbee5c7
