### ISSUE TITLE
Cached comments are not updated correctly

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#316]
1. Open comments for a post that have a number of comments
2. Check text of the comments visible on the screen
3. Modify comment attributes of some comments from another device (e.g. like, add a reply)
4. Restart the app
5. Open comment for the same post
6. Cheсk text of the same comment

Current result:
Comment text will be the same until comments will be scrolled in way to hide comment from the screen and then display it back

The easiest way to reproduce the issue is to run the following test and put a breakpoint after openScreen call in the second step:

class BugRepro: UITestBase {
    var sideMenu: SideMenu!
    var feed: Feed!
    var comments: CommentsFeed!
    
    override func setUp() {
        super.setUp()
        sideMenu = SideMenu(app)
        feed = Feed(app)
        comments = CommentsFeed(app)
    }
    
    func openScreen() {
        sideMenu.navigateTo("Home")
        let post = feed.getPost(0)
        post.teaser.tap()
        sleep(1)
    }
    
    func testCommentCacheStep1() {
        APIConfig.values = ["text": "Initial Text"]
        openScreen()
    }
    
    func testCommentCacheStep2 () {
        APIConfig.values = ["text": "Modified Text"]
        openScreen()
        
    }
}

**Comment by orezhko** [comment]
Jaroslaw, could you please verify it was fixed or not

**Comment by orezhko** [comment]
can't be reproduced on the latest version from develop
