### ISSUE TITLE
Feed Service does not cache response with zero items.

### ISSUE THREAD

**Issue by IgorPopov-MS** [Microsoft/EmbeddedSocial-iOS-SDK#398]

**Comment by IgorPopov-MS** [comment]
This issue was introduced with requestExecutionStrategy in TopicService.

**Comment by Vadim-Bulavin** [comment]
Confirmed by @IgorPopov-MS that it's not requestExecutionStrategy issue.

**Comment by IgorPopov-MS** [comment]
closing this ticket since it does not reproduce.
