### ISSUE TITLE
UI: Incorrect feed layout in post details.

### ISSUE THREAD

**Issue by mrdevms** [Microsoft/EmbeddedSocial-iOS-SDK#402]
1) Go to topic details.
2) Scroll to hide feed module 
3) Open report some comment screen
4) Dismiss report screen.
5) Scroll to feed module and you will see the problem.

![img_0088](https://user-images.githubusercontent.com/5517704/31944865-2b31216e-b8d6-11e7-90a8-c6e0cd98b67f.PNG)

**Comment by JaroslawRomanovich** [comment]
The problem is active on build from commit number 949aa726711635969e6cb57e2adf4ac9951e3a17
