### ISSUE TITLE
[Manual] - Incorrect indent between action buttons and bottom edge for post

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#436]
Commit number: 69c7f7816de44a20c5b096ec9199738882d5171f

Preconditions: 
- Popular tabs contain posts

Steps to reproduce:
1. Install a new version of the application
2. Launch the application and sign in
3. Open "Popular" screen
4. Open "All Time" feed

Actual Result: Incorrect indent between action buttons and bottom edge for the first post in the feed (the same issue sometimes appears on "Post" screen)
![img_0059](https://user-images.githubusercontent.com/5517704/31174728-33c93cf6-a915-11e7-9dd9-bb9fdf0019e1.PNG)

Expected Result: All posts in the feed have the same correct intends between elements

**Comment by IgorPopov-MS** [comment]
fixed in #438
