### ISSUE TITLE
[Manual] - Incorrect view of post in gallery view 

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#448]
Commit number: 541de36

Preconditions: Test user is signed in

Steps to reproduce:

1. Open "Popular" feed with posts
2. Change "List" view to "Gallery" view and backward several times 
3. Open several posts and update this posts by comments\replies
4. Repeat steps 2-3 several times

Actual Result:  Posts in gallery view have incorrect images (re-sized image of a post in list view)
![img_0060](https://user-images.githubusercontent.com/5517704/31229444-5a965e02-a9e9-11e7-9b3d-ea74d25763bd.PNG)

Expected Result: Posts in gallery view have correct images

**Comment by IgorPopov-MS** [comment]
Log of the bug:
17:45:10 🔥🔥🔥[FeedModulePresenter.swift]:processFetchResult(feed:isMore:) -> [Optional("items arrived")]
17:45:10 🔥🔥🔥[FeedModuleViewController.swift]:reload() -> [Optional("visible:"), Optional(0), Optional("available:"), Optional(7)]
17:45:10 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 0]), Optional("PostCell")]
17:45:10 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 1]), Optional("PostCell")]
17:45:10 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 1]), Optional("PostCell")]
17:45:11 🔥🔥🔥[FeedModulePresenter.swift]:processFetchResult(feed:isMore:) -> [Optional("items arrived")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:reloadVisible() -> [Optional([[0, 1], [0, 0]])]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 0]), Optional("PostCell")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 1]), Optional("PostCell")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:onUpdateLayout(type:animated:) -> [Optional("visible:"), Optional(2), Optional("available:"), Optional(7)]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:onUpdateLayout(type:animated:) -> [Optional("changed layout"), Optional(EmbeddedSocial.FeedModuleLayoutType.grid)]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 6]), Optional("PostCellCompact")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 4]), Optional("PostCellCompact")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 2]), Optional("PostCellCompact")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 5]), Optional("PostCellCompact")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:collectionView(_:cellForItemAt:) -> [Optional("cell ->"), Optional([0, 3]), Optional("PostCellCompact")]
17:45:11 🔥🔥🔥[FeedModuleViewController.swift]:reloadVisible() -> [Optional("reload visible:"), Optional(7), Optional("available:"), Optional(7)]
