### ISSUE TITLE
[Manual] - The "Processing" spinner is displayed over the side panel

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#450]
Commit number: 541de36

Preconditions: Test user is signed in

Steps to reproduce:
1. Open "Popular" feed
2. Open a tab on the "Popular" screen that needs data loading
3, Open side panel during data loading on the tab

Actual Result: The "Processing" spinner is displayed over the side panel
![img_0065](https://user-images.githubusercontent.com/5517704/31235248-abd8a53a-a9f9-11e7-8e83-858d4450ae3f.PNG)

Expected Result: Data updating should not affect side panel by the "Processing" spinner

**Comment by IgorPopov-MS** [comment]
<img width="1440" alt="screen shot 2017-10-10 at 1 36 49 pm" src="https://user-images.githubusercontent.com/29776360/31382379-21c3311a-adc0-11e7-8864-b322685c843f.png">

**Comment by orezhko** [comment]
Let's use https://github.com/jdg/MBProgressHUD - it can be displayed on a subview
