### ISSUE TITLE
[Manual] - Error message is displayed after opening of "Profile" screen in offline mode

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#469]
Commit number: bc9d25e

Preconditions: Test user is signed in

Steps to reproduce:
1. Open "Home" screen
2. Turn off network connection on device under test 
3. Open "Profile" screen

Actual Result: The "Unknown error occurred" message is displayed on the screen
Expected Result: No error  message is displayed to the user. Notification about offline mode "You can still post while offline." is displayed on the screen.

NOTE: The same issue for "Search" screen

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich implemented

**Comment by JaroslawRomanovich** [comment]
Verified in build from commit number 949aa726711635969e6cb57e2adf4ac9951e3a17
