### ISSUE TITLE
[Manual] - Functionality for posts removing does not work in offline mode

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#473]
Commit number: bc9d25e

Preconditions: 
- Test user is signed in;
- Test user has posts;

Steps to reproduce:

1. Open "Profile" screen
2. Turn off network connection on device under test
3. Add a new post in offline mode
4. Delete a post that was added in on-line mode
5. Delete the post that was added in offline mode
6. Pull down the screen to refresh

Actual Result: Both removed posts are displayed on the screen
Expected Result: Both removed posts are not displayed on the screen

**Comment by orezhko** [comment]
We have a crash in that functionality on the latest build from develop

**Comment by JaroslawRomanovich** [comment]
Unable to reproduce on the latest build from commit 949aa726711635969e6cb57e2adf4ac9951e3a17
