### ISSUE TITLE
[Manual] - Counter for comments does not changing in offline mode

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#493]
Commit number: bc9d25e

Preconditions:
- Test user is signed in;

Steps to reproduce:

1. Set the application to offline mode
2. Open "Popular" feed 
3. Add a comment to a post
4. Check "Comments" counter for the post

Actual Result: Counters for comments does not changing in offline mode
Expected Result: Counters for comments should changing in offline mode the same as in on-line mode

**Comment by orezhko** [comment]
Jaroslaw, could you please try to reproduce that issue on develop branch after 43b638f6ec60521241368aae92736d21f5a67da4 commit

**Comment by JaroslawRomanovich** [comment]
The problem is still active in build from commit number 949aa72

**Comment by JaroslawRomanovich** [comment]
The problem is still active on "Post" screen on build from commit number 73646af7c86417b3aacb7aadf4c5b0b196e4e00a

**Comment by JaroslawRomanovich** [comment]
Verified for feed on build fro commit number 73646af
