### ISSUE TITLE
[Manual] - Incorrect owner of follow request is displayed on "New follow requests" screen

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#500]
Commit number: bc9d25e

Preconditions:
- Two test users (User1 and User2) are used for testing;
- Second test user (User2) has "Only approved followers..." options is turned on;
- First test user (User1) is signed in;

Steps to reproduce:
Add a follow request to User2 by User1
Sign out User1
Sign in as User2
Open "New follow requests" screen

Actual Result: User2 is displayed on "New follow requests" screen (User2 will be added to "followers" of himself if he accepts the follow request)
Expected Result: User1 is displayed on "New follow requests" screen

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich seems like a server issue. I wasn't able to reproduce it.

**Comment by orezhko** [comment]
Let's keep our eyes on that issue during next few days

**Comment by JaroslawRomanovich** [comment]
Verified on build from commit number 9b800d22b82f4aa70239a721cf3dd5dc7d5c7bdb
