### ISSUE TITLE
[Manual] - The application crashes after an attempt to remove post from search results

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#503]
Commit number: bc9d25e

Preconditions:
- Test user is signed in;

Steps to reproduce:

1. Add a post with hash tag (e.g."#coffee.") that has search results in title
2. Open "Search" screen
3. Search for the hash tag  ("#coffee.")
4. Open menu with action for the post in the search results that was created by the test user
5. Tap on "Remove" item in the menu

Actual Result: The application crashes
Expected Result: The post is removed from search results and for the user

**Comment by IgorPopov-MS** [comment]
It requires creation of offline "PostRemove" commands, which will be applied to cache responses.
