### ISSUE TITLE
[Manual] - Incorrect width of posts on "Profile" screen

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#506]
Commit number: c643e5da3f9d1c5df634d5a71791aba349d33d7c

Preconditions:
- Test user is signed in;
- Test user has posts;

Steps to reproduce: 
Open "Profile" screen
Check width of posts on the screen

Actual Result: Posts have incorrect width
![img_0072](https://user-images.githubusercontent.com/5517704/31432196-983e8e0c-ae7e-11e7-9deb-6afc53c58f1f.PNG)

Expected Result: Posts have the same width as all other elements on the screen

**Comment by IgorPopov-MS** [comment]
Fixed indicator, 
assigning on @Vadim-Bulavin for header fix.
PR #527
