### ISSUE TITLE
[Manual] - Comment that was added in offline disappears after pull to refresh operation

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#515]
Commit number: c643e5d

Preconditions:
- Test user is signed in;

Steps to reproduce:

1. Add a comment to a post in offline
2. Turn on network connection on device under test
3. Open the posts with added comments 
4. Pull down the screen to refresh
5. Pull down the screen to refresh

Actual Result: 
after step 4: The comment disappears after pull to refresh operation
after step 5: The comment appears after second pull to refresh operation

Expected Result: 
after step 4: The comment is displayed for the post
after step 5: The comment is displayed for the post

**Comment by mrdevms** [comment]
@Vadim-Bulavin, please make sure that the deletion of the outgoing command is correct.
