### ISSUE TITLE
[Auto Test] - "All time" popular items does not cached

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#533]
Steps to reproduce:

1. Open "Popular" screen
2. Select "All time" segment item
3. Disable network connection
4. Pull to refresh

Actual result: "No content" label displays
Expected result: Cached items displays

**Comment by oboje** [comment]
I've rechecked on device using steps provided.
Cache works.
I've rechecked app with mocked server, it does hit cache.

**Comment by IgorPopov-MS** [comment]
I've rechecked on device using steps provided.
Cache works.
I've rechecked app with mocked server, it does hit cache.
