### ISSUE TITLE
some screens are still missing spinners

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#542]
Repro:
1. go to a popular topic feed
2. pin a topic
3. go to your pins
4. you will see your previous pin feed (empty or whatever you had previously pinned). eventually you will see the latest pinned topic

There is no indication that the pin feed is still refreshing.

Similar behavior when I go to my user profile and wait for my topic feed to load.

Please check all feeds.

**Comment by orezhko** [comment]
The current logic is:
1) Request data from server
2) Show wait indicator
3) Get data from cache (if they are available) and hide indicator
4) User can start scrolling/browsing content
5) Update data based on the server response

Could you please confirm that we need to show wait indicator until we get a response from server

**Comment by sharadagarwal** [comment]
Can we have a visual indicator for loading that does not prevent the user from scrolling & browsing existing content?

**Comment by sharadagarwal** [comment]
I see similar behavior when I click on a hashtag - it goes to search, and I get an empty topic feed and a little bit later a topic shows up.
