### ISSUE TITLE
search history should not show empty list

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#543]
![img_3711](https://user-images.githubusercontent.com/5649639/31524155-ad6267ba-af6c-11e7-9c3b-2b4b4dc5e56c.PNG)

If I don't have any past search queries, then don't show me a search history. If I have only 1 or a few past search queries, then show only those.

**Comment by orezhko** [comment]
this was a part of the tests for search history - disabled it
