### ISSUE TITLE
Facebook login permissions should not ask for your friends list

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#597]
When logging in, the app asks for user profile, email address, and friends list. It should not ask for the friends list. The friends list should only be requested when calling users/me/following/suggestions/users .

**Comment by Vadim-Bulavin** [comment]
@orezhko @sharadagarwal The requested permission is https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_friends and it's required for users/me/following/suggestions/users to work. Otherwise EmbeddedSocial API call users/me/following/suggestions/users returns errors.

**Comment by sharadagarwal** [comment]
When logging in, the Android SDK uses the permissions on line 131 from [sample1](https://github.com/Microsoft/EmbeddedSocial-Android-SDK/blob/38d85b6973f44c2091890047f1ad1080495722c8/EmbeddedSocialClient/sdk/src/main/java/com/microsoft/embeddedsocial/auth/FacebookAuthenticator.java#L136) , and when finding friends, it uses the permissions on line 136.

**Comment by orezhko** [comment]
Yea, we need to repeat that on iOS as well and use different permissions for sign-in and find friends operations

**Comment by JaroslawRomanovich** [comment]
Verified on the build from commit number 0e8e7126865d5ac106e04482326f059a9af96579
