### ISSUE TITLE
[Manual] - Different indent from the top of "Profile" screen for tabs

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#600]
Commit number: 12778db

Preconditions: 
- Test user is signed in;
- "Recent posts" tab has posts on "Profile" screen;  
- "Popular posts" tab does not have posts on "Profile" screen;

Steps to reproduce:

1. Open "Profile" screen 
2. Switch between "Recent posts" and "Popular posts" tabs

Actual Result: Indent from the top of "Profile" screen for "Popular posts" tabs is bigger than for  "Recent posts"tab
![img_0082](https://user-images.githubusercontent.com/5517704/31878783-e03ddf96-b7e3-11e7-93b8-000ecd4df611.PNG)

Expected Result: Both tabs on "Profile" screen have the same layout of elements

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich can't reproduce in 61d7a17888be447e9c94794ec608281e3372adf1
![image](https://user-images.githubusercontent.com/29773899/31885478-4f6321dc-b7f9-11e7-8fb6-ef4e18720598.png)

**Comment by Vadim-Bulavin** [comment]
implemented in https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/pull/605

**Comment by JaroslawRomanovich** [comment]
Verified on the build from commit number 15a30d33a46d25d659c7dadcbce3bbe49c4a1284
