### ISSUE TITLE
[Manual] - Comment is closed after adding of a reply in offline

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#603]
Commit number: 12778db

Preconditions: Test user is signed in;

Steps to reproduce:

1. Open a comment with several pages of replies
2. Set the application to offline mode
3. Add a reply to the comment

Actual Result: The "Comment" screen is closed
Expected Result: The "Comment" screen is opened and the added reply is displayed

**Comment by mrdevms** [comment]
Сould not reproduce.

**Comment by orezhko** [comment]
Jaroslaw reproduced it in 100%

**Comment by JaroslawRomanovich** [comment]
Verified on the build from commit number 949aa726711635969e6cb57e2adf4ac9951e3a17
