### ISSUE TITLE
Fix NSInternalInconsistencyException in - [NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#607]
### Reason ###

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionFooter at path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192097023](https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192097023)

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich seems like an old crash on feed when the layout was changed from grid to list. Think we've located and fixed it.

**Comment by JaroslawRomanovich** [comment]
Unable to reproduce on build from commit number 9b800d22b82f4aa70239a721cf3dd5dc7d5c7bdb
