### ISSUE TITLE
Fix crash in - [UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:]

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#609]
### Reason ###

No reason found. Full stack trace includes libswiftCore.dylib, UIKit, QuartzCore, libdispatch.dylib, CoreFoundation, GraphicsServices, libdyld.dylib.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192115692](https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192115692)

**Comment by IgorPopov-MS** [comment]
@sharadagarwal that was fixed in PR #634 .
I assume i may close it?
