### ISSUE TITLE
somehow got to a strange UI

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#610]
![img_3716](https://user-images.githubusercontent.com/5649639/31903573-58cd5196-b7dd-11e7-8251-dd37f222610e.PNG)

I don't have a report. I was clicking around in the app, and somehow got to the UI above. I don't think this UI is expected behavior.

**Comment by JaroslawRomanovich** [comment]
Unable to reproduce on build from commit number 15a30d33a46d25d659c7dadcbce3bbe49c4a1284
