### ISSUE TITLE
[Manual] - Duplication of comments\replies that were added in offline mode

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#614]
Commit number: 949aa726711635969e6cb57e2adf4ac9951e3a17

Preconditions: Test user is signed in;

Steps to reproduce:

1. Set the application to offline mode
2. Add several (5-10) comments\replies for comments
3. Set the application to on-line mode
4. Wait for data synchronization
5. Check comments or replies that were added in offline mode

Actual Result: Some comments and replies are duplicated
Expected Result: No duplication of comments and replies

**Comment by mrdevms** [comment]
Reproduced on post creation too.

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich implemented in https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/pull/647

**Comment by JaroslawRomanovich** [comment]
Verified on build from commit number 73646af7c86417b3aacb7aadf4c5b0b196e4e00a
