### ISSUE TITLE
Add delete user functionality to settings page

### ISSUE THREAD

**Issue by orezhko** [Microsoft/EmbeddedSocial-iOS-SDK#623]
When user click on warning we need to display a confirmation message:

"This action will permanently delete your account and all associated information. The account deletion cannot be undone.\n\nDo you really want to do it?"

and buttons "delete" and "cancel". if user press "delete" we need to invoke API call to delete account, search history and then switch to the public/not authorized mode

**Comment by JaroslawRomanovich** [comment]
Verified on build from commit number 2be778f8f31728dd41a25cd85e5fdfc391969a3f
