### ISSUE TITLE
Fix crash in readARCWeakAtWithSentinel

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#645]
### Reason ###

No reason found. Full stack trace includes Foundation, libswiftCore.dylib, libdispatch.dylib, libsystem_pthread.dylib.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192698015](https://rink.hockeyapp.net/manage/apps/632649/crash_reasons/192698015)

**Comment by IgorPopov-MS** [comment]
@sharadagarwal 
Im confident that this crash is related collection view issues that were fixed in PR #634.
