### ISSUE TITLE
[Manual] - Incorrect indent between elements on "Activity Feed" after several pull to refresh operations

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#652]
Commit number: e3e3c42

Preconditions: Test user is signed in

Steps to reproduce:
1. Open "Activity Feed" screen
2. Pull down the screen to update several times

Actual Result: Incorrect indent between tabs and first sections (additional space for "processing" spinner is displayed on the screen)
![img_0098](https://user-images.githubusercontent.com/5517704/32111814-49a85304-bb44-11e7-9fb8-2fd358f3dda3.PNG)

Expected Result: Layout of elements should be in accordance with the requirements

**Comment by orezhko** [comment]
Should be fixed, please verify on the latest version from develop

**Comment by JaroslawRomanovich** [comment]
Verified on a build from commit number 7f3d09256e9b78b6e4cd0207ad47b75f4691d65e
