### ISSUE TITLE
unable to press & select text in topic/comment/reply (e.g. to copy text from a previous post)

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#666]

**Comment by orezhko** [comment]
Verified on Android - it is possible to copy text from text edit controls (not from labels and other text on screen). We have the same behavior on iOS

**Comment by sharadagarwal** [comment]
I tried out olkol/copyable_label . When I press and hold, it shows me the following screen:
<img width="283" alt="screen shot 2017-11-06 at 4 24 29 pm" src="https://user-images.githubusercontent.com/5649639/32470829-292fb1da-c30f-11e7-9b4f-5bcc8a2c9b8a.png">

It doesn't show me what part of the text is being selected.

**Comment by orezhko** [comment]
Full text is copied, there is no way to specify what part of UILabel should be copied without significant changes and again we don't have that functionality on Android where you can copy text from edit controls only
