### ISSUE TITLE
make POST actions non-blocking on the UI

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#676]
Sometimes, posting a topic, comment, reply, image can take a long time, such as when the client's network is slow. Currently, the UI blocks with a spinner until the action completes or fails. We should consider making the UI not block so that the user can continue to do other things in the app. This needs to be thought through carefully, considering:
- what happens if the original action results in a failure
- what happens if the user starts doing multiple actions
- what happens if the user wants to do an action on the thing that they are posting (e.g. delete, edit, like)
- what happens if the user closes the app before the action completes; are they aware that the action did not complete?

**Comment by sharadagarwal** [comment]
@orezhko : I believe the Android SDK does some of this.

**Comment by orezhko** [comment]
I verfied on Android - it doesn't support copy operation for texts. You can copy text from editfields only. We have a branch with trequested change and can easily merge it to develop if you want

**Comment by orezhko** [comment]
branch name olkol/copyable_label
