### ISSUE TITLE
[Manual] - Deletion of search history does not work

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#689]
Commit number: d6c3226

Preconditions: 
- Test user is sighed in;
- Search history exists for both "Topics" and "People";

Steps to reproduce:
1. Open "Settings" screen
2. Tap on "Delete search history" button
3. Open "Search" screen
4. Set focus to a search field on "Search" screen

Actual Result: The search history list is opened for the field 
Expected Result: No search history for both tabs - "Topics" and "People"

**Comment by Vadim-Bulavin** [comment]
@JaroslawRomanovich can't reproduce. Tested on:
Simulator: iOS 10.3, 11.1
Device: iPhone 6s, iOS 11.1

**Comment by JaroslawRomanovich** [comment]
Verified on build from commit number 0e8e712
