### ISSUE TITLE
[Manual] - No records for activity feed when notifications for "Activity Feed" item exist in the menu

### ISSUE THREAD

**Issue by JaroslawRomanovich** [Microsoft/EmbeddedSocial-iOS-SDK#690]
Commit number: d6c3226

Preconditions: 
- Test user is sighed in;
- Notifications about new records for "Activity Feed" item exist in the menu; 

Steps to reproduce:
1. Open "Activity Feed" screen
2. Check both tabs - "You" and "Following"

Actual Result: Both feeds are empty
Expected Result: One of the feed has number of records that is at least equal to a number of new records in the notification in the menu

**Comment by orezhko** [comment]
Should be fixed, please verify develop

**Comment by JaroslawRomanovich** [comment]
Verified on a build from commit number 7f3d09256e9b78b6e4cd0207ad47b75f4691d65e
