### ISSUE TITLE
new comment post does not update topic cards

### ISSUE THREAD

**Issue by sharadagarwal** [Microsoft/EmbeddedSocial-iOS-SDK#768]
1. click on a topic
2. add a new comment
3. comment count for that topic does not auto-update; pull-to-refresh updates it
4. go back; the topic card in the feed also does not show the new comment count

Similar behavior when deleting a comment.

**Comment by sharadagarwal** [comment]
item 3 above is fixed, but item 4 isn't. The topic card in the topic feed still shows the old comment count.

**Comment by orezhko** [comment]
we can't reproduce this issue - maybe in your case it was related to the fact that client wasn't able to download updated feed after successful comment posting or server return the incorrect number of comments in response
